GET http://localhost:3001/api/blogs
###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "jiko",
  "author": "tony",
  "url": "http://123jokk.com",
  "likes": "999",
  "userid": "5ecb7786bf47de0aa014ff0b"
}
###

DELETE http://localhost:3001/api/blogs/5ec779c11e53cb0f9c1f
###

PUT http://localhost:3001/api/blogs/5ec78f37e5743714d
Content-Type: application/json

{
  "title": "test put",
  "url": "http://testurl.com",
  "author": "tony",
  "likes": 9999
}



### user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "tony222",
  "name": "ty",
  "password": "1111"
}
###

GET http://localhost:3001/api/users
