POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "j123",
  "number": 12345678
}
###

PUT http://localhost:3001/api/persons/5ec4a0b5be8e4825e00d51a9
Content-Type: application/json

{
  "name": "alast222",
  "number": 456456
}
###

GET http://localhost:3001/api/persons
###

GET http://localhost:3001/api/persons/fdsfwe123213213
###

DELETE http://localhost:3001/api/persons/5ec4bcc03b924733fc8a9580
###