DELETE http://localhost:3001/api/persons/5ec3a10fad93f02a0418aa91
###

GET http://localhost:3001/api/persons/5ec3a10fad93f02a0418aa91
###

GET http://localhost:3001/api/persons
###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "monika3",
  "number": 11111
}
###

PUT http://localhost:3001/api/persons/5ec3a10fad93f02a0418aa91
Content-Type: application/json

{
  "name": "666",
  "number": 456456
}