GET http://localhost:3001/api/blogs
###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "test222",
  "author": "tony222",
  "url": "http://asdfasdf.com",
  "likes": "2222222"
}